//////////////////////////////////////////////////////////////////////
// This file is part of Remere's Map Editor
//////////////////////////////////////////////////////////////////////

// Battle Royale: what the loot palette offers -- the tiers (with the name the HUB
// gave them) and the items of the loot table, each with its server id for the
// sprite.
//
// It is GENERATED by make_loot_zones.py into the client data folder of the editor
// (data/<version>/battleroyale_loot_catalog.json). The editor never decides what is
// loot: the list is the server's BRLoot.entries, and the vision cut hides exactly
// that list -- an item outside it would be seen through walls.
//
// Without the file the zones still work (tiers fall back to plain numbers); only
// placing items by hand needs it.

#ifndef RME_BR_LOOT_CATALOG_H_
#define RME_BR_LOOT_CATALOG_H_

#include "app/main.h"

#include <chrono>
#include <cstdint>
#include <string>
#include <vector>

class BRLootCatalog {
public:
	struct Tier {
		int tier = 0;
		std::string label;
	};
	struct Entry {
		std::string name;
		uint16_t server_id = 0;
	};

	// Re-reads the file when it changed on disk. Cheap enough to call every frame:
	// the disk is only asked once a second (or every call with `force`).
	void refresh(bool force = false);

	bool isLoaded() const {
		return loaded;
	}
	wxString getPath() const;
	// Bumped on every successful (re)load, so a palette knows when to rebuild.
	uint32_t getVersion() const {
		return version;
	}

	const std::vector<Tier>& getTiers() const {
		return tiers;
	}
	// Sorted by name.
	const std::vector<Entry>& getEntries() const {
		return entries;
	}
	// Empty when the tier is not in the file.
	std::string tierLabel(int tier) const;
	// 0 when the name is not in the catalog.
	uint16_t serverIdOf(const std::string& name) const;

private:
	bool load(const wxString& path);

	bool loaded = false;
	uint32_t version = 0;
	wxString loaded_path;
	time_t loaded_mtime = 0;
	std::chrono::steady_clock::time_point last_check {};
	bool checked_once = false;
	std::vector<Tier> tiers;
	std::vector<Entry> entries;
};

extern BRLootCatalog g_br_loot_catalog;

#endif
